import { datePickerAnatomy } from "@ark-ui/svelte/anatomy";

import { defineSlotRecipe } from "@pandacss/dev";

/**
 * Chrome for Ark UI's DatePicker in range mode. The calendar's selection state is
 * communicated entirely through data attributes Ark sets on the cell trigger —
 * `data-selected` for the two endpoints, `data-in-range` for the days between,
 * `data-outside-range` for spillover days — so the visual range is styled off
 * those rather than any component state we track.
 */
export const datePickerRecipe = defineSlotRecipe({
	className: "datepicker",
	description: "Ark DatePicker range calendar",
	slots: datePickerAnatomy.keys(),
	base: {
		control: {
			display: "flex",
			alignItems: "center",
			gap: "0.35rem",
		},
		input: {
			width: "6.5rem",
			paddingBlock: "0.3rem",
			paddingInline: "0.5rem",
			font: "inherit",
			fontSize: "0.82rem",
			color: "text",
			bg: "panel",
			border: "1px solid token(colors.border)",
			borderRadius: "5px",
			fontVariantNumeric: "tabular-nums",
			_focusVisible: { outline: "none", borderColor: "accent" },
		},
		trigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "2rem",
			height: "2rem",
			color: "muted",
			borderRadius: "5px",
			cursor: "pointer",
			_hover: { bg: "selection", color: "text" },
		},
		content: {
			zIndex: 20,
			padding: "0.75rem",
			bg: "panel",
			color: "text",
			border: "1px solid token(colors.border)",
			borderRadius: "10px",
			boxShadow: "menu",
			_focusVisible: { outline: "none" },
		},
		viewControl: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: "0.5rem",
			marginBottom: "0.5rem",
		},
		prevTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "1.9rem",
			height: "1.9rem",
			borderRadius: "5px",
			cursor: "pointer",
			color: "muted",
			_hover: { bg: "selection", color: "text" },
		},
		nextTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "1.9rem",
			height: "1.9rem",
			borderRadius: "5px",
			cursor: "pointer",
			color: "muted",
			_hover: { bg: "selection", color: "text" },
		},
		viewTrigger: {
			flex: 1,
			paddingBlock: "0.3rem",
			fontWeight: 600,
			fontSize: "0.86rem",
			borderRadius: "5px",
			cursor: "pointer",
			_hover: { bg: "selection" },
		},
		table: {
			borderCollapse: "collapse",
			width: "100%",
		},
		tableHeader: {
			paddingBlock: "0.25rem",
			fontSize: "0.7rem",
			fontWeight: 500,
			color: "muted",
			textTransform: "uppercase",
		},
		tableCell: {
			padding: 0,
			textAlign: "center",
		},
		tableCellTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minWidth: "2rem",
			height: "2rem",
			paddingInline: "0.4rem",
			fontSize: "0.8rem",
			borderRadius: "5px",
			cursor: "pointer",
			fontVariantNumeric: "tabular-nums",
			_hover: { bg: "selection" },
			_selected: { bg: "accent", color: "#ffffff", _hover: { bg: "accent.strong" } },
			_disabled: { opacity: 0.35, cursor: "default", _hover: { bg: "transparent" } },
			"&[data-in-range]": { bg: "selection", borderRadius: 0 },
			"&[data-first-in-range]": { borderTopLeftRadius: "5px", borderBottomLeftRadius: "5px" },
			"&[data-last-in-range]": { borderTopRightRadius: "5px", borderBottomRightRadius: "5px" },
			"&[data-outside-range]": { color: "muted", opacity: 0.5 },
			"&[data-today]": { boxShadow: "inset 0 0 0 1px token(colors.accent)" },
		},
		presetTrigger: {
			paddingBlock: "0.3rem",
			paddingInline: "0.55rem",
			font: "inherit",
			fontSize: "0.78rem",
			fontWeight: 500,
			color: "text",
			bg: "transparent",
			border: "1px solid token(colors.border)",
			borderRadius: "999px",
			cursor: "pointer",
			whiteSpace: "nowrap",
			_hover: { bg: "selection", borderColor: "accent" },
			_disabled: {
				opacity: 0.4,
				cursor: "default",
				pointerEvents: "none",
				_hover: { bg: "transparent", borderColor: "border" },
			},
		},
	},
});
